version: '3.9'

services:
    be-campaigns:
        environment:
            - DB_RO=${DB_RO_CAMPAIGN}
            - DB_RW=${DB_RW_CAMPAIGN}
            - DB_ID=${DB_ID_CAMPAIGN}
            - CONTAINER_ID=${CONTAINER_ID_CAMPAIGN}

        build:
            context: ./be-campaigns

        image: sv_be-campaigns

        ports:
            - target: 9002
              published: 9002

        networks:
            - net-pub

    fe-web-api:
        environment:
            - AUTH_URI=${B2C_AUTH_URI}
            - BE_CAMPAIGNS_URL=http://be-campaigns:9002

        build:
            context: ./fe-web-api

        image: sv_fe-web-api

        ports:
            - target: 9000
              published: 9000

        networks:
            - net-pub

    fe-web:
        build:
            context: ./fe-web-react
            args:
                - ARG_B2C_LOGIN_URL=${B2C_LOGIN_URL}
                - ARG_B2C_TENANT=${B2C_TENANT}
                - ARG_B2C_USERFLOW_NAME=${B2C_USERFLOW_NAME}
                - ARG_B2C_APP_ID=${B2C_APP_ID}
                - ARG_FE_AUTH_URL_REDIRECT=${AUTH_URL_REDIRECT}
                - ARG_FE_AUTH_URL_REDIRECT_POST_SIGNOUT=${AUTH_URL_REDIRECT_POST_SIGNOUT}
                - ARG_FE_WEB_API_URL=http://fe-web-api:9000

        image: sv_fe_web

        ports:
            - target: 8000
              published: 8000

        networks:
            - net-pub

networks:
    net-pub:
        name: silly-votes-net-pub
