const Actions = {
    ADD_CAMPAIGN: "ADD_CAMPAIGN",
    CHANGE_CAMPAIGNS: "CHANGE_CAMPAIGNS",
    CHANGE_LOADING: "CHANGE_LOADING",
    CLOSE_DETAILS: "CLOSE_DETAILS",
    EDIT_CAMPAIGN: "EDIT_CAMPAIGN",
    REMOVE_CAMPAIGN: "REMOVE_CAMPAIGN"
};

export default Actions;
