const Actions = {
    ADD_CAMPAIGN: 'ADD_CAMPAIGN',
    CAMPAIGN_SAVE_SUCCESS: 'CAMPAIGN_SAVE_SUCCESS',
    CHANGE_CAMPAIGNS: 'CHANGE_CAMPAIGNS',
    CLOSE_DETAILS: 'CLOSE_DETAILS',
    EDIT_CAMPAIGN: 'EDIT_CAMPAIGN',
    INIT_FINISHED: 'INIT_FINISHED',
    REMOVE_CAMPAIGN_FAIL: 'REMOVE_CAMPAIGN_FAIL',
    REMOVE_CAMPAIGN_INIT: 'REMOVE_CAMPAIGN_INIT',
    REMOVE_CAMPAIGN_SUCCESS: 'REMOVE_CAMPAIGN_SUCCESS',
    SAVE_CAMPAIGN_FAIL: 'SAVE_CAMPAIGN_FAIL',
    SAVE_CAMPAIGN_INIT: 'SAVE_CAMPAIGN_INIT',
    SAVE_CAMPAIGN_SUCCESS: 'SAVE_CAMPAIGN_SUCCESS',
    UPDATE_CAMPAIGN_FAIL: 'UPDATE_CAMPAIGN_FAIL',
    UPDATE_CAMPAIGN_INIT: 'UPDATE_CAMPAIGN_INIT',
    UPDATE_CAMPAIGN_SUCCESS: 'UPDATE_CAMPAIGN_SUCCESS'
};

export default Actions;
